import java.io.*;
import java.lang.management.*;
import java.net.*;
import java.nio.file.*;

public class SystemMonitor {

    public static void main(String[] args) throws Exception {
        OperatingSystemMXBean osBean = ManagementFactory.getOperatingSystemMXBean();
        Runtime runtime = Runtime.getRuntime();

        int cpuCores = osBean.getAvailableProcessors();
        long freeMemory = runtime.freeMemory() / (1024 * 1024);
        long totalMemory = runtime.totalMemory() / (1024 * 1024);
        long usedMemory = totalMemory - freeMemory;

        File diskPartition = new File("/");
        long totalDisk = diskPartition.getTotalSpace() / (1024 * 1024 * 1024);
        long freeDisk = diskPartition.getFreeSpace() / (1024 * 1024 * 1024);
        long usedDisk = totalDisk - freeDisk;

        InetAddress ip = InetAddress.getLocalHost();
        String hostName = ip.getHostName();
        String ipAddress = ip.getHostAddress();

        String htmlContent = "<!DOCTYPE html>\n<html>\n<head>\n<title>System Health Dashboard</title>\n"
                + "<style>\n"
                + "body { font-family: 'Times New Roman', serif; background-color: #ffe6f2; color: #333; text-align: center; }\n"
                + "h1 { color: #cc0066; }\n"
                + ".card { background: white; margin: 20px auto; padding: 20px; border-radius: 15px; width: 50%; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }\n"
                + ".metric { font-size: 18px; margin: 10px; }\n"
                + "</style>\n</head>\n<body>\n"
                + "<h1>Endpoint Health and Performance Dashboard</h1>\n"
                + "<div class='card'>"
                + "<div class='metric'><b>Host Name:</b> " + hostName + "</div>"
                + "<div class='metric'><b>IP Address:</b> " + ipAddress + "</div>"
                + "<div class='metric'><b>CPU Cores:</b> " + cpuCores + "</div>"
                + "<div class='metric'><b>Used Memory:</b> " + usedMemory + " MB / " + totalMemory + " MB</div>"
                + "<div class='metric'><b>Used Disk:</b> " + usedDisk + " GB / " + totalDisk + " GB</div>"
                + "</div>\n"
                + "<footer><p>Generated by Java Endpoint Monitor © 2025</p></footer>"
                + "</body>\n</html>";

        Files.write(Paths.get("system_dashboard.html"), htmlContent.getBytes());
        System.out.println("✅ System Health Dashboard generated: system_dashboard.html");
    }
}
